"""Rigor de la tanda 625 — el repaso de los efectos del formato.

Cada mutación rompe el ORIGEN: la plantilla que lee la frase, la traducción
que la lleva del español al inglés, o el paso del motor que la hace. No una
guarda de repuesto."""
import sys
sys.path.insert(0, '/tmp/claude-0/-home-user/b9afdd5d-e7a3-5d00-bfc6-d85d45049058/scratchpad')
import rigor_comun

PAR = 'js/constructor/partida.js'
TXT = 'js/constructor/textos.js'
ES = 'js/constructor/textos-es.js'
EFE = 'js/constructor/efectos.js'

MUTACIONES = [
    # ── El daño (calcularPorTexto) ──
    (PAR, 'las herramientas cuentan solo la del activo',
     "          const propias = this.enJuego.filter((x) => x.herramienta).length",
     "          const propias = this.s.activo?.herramienta ? 1 : 0"),
    (PAR, '«Pokémon Evolución» también es un básico',
     "p.fase === 'evolucion' ? faseDe(cr) > 0 : faseDe(cr) === p.fase",
     "p.fase === 'evolucion' ? faseDe(cr) >= 0 : faseDe(cr) === p.fase"),
    (PAR, '«por lo menos 3 energías» pide 4',
     "energiasDe(x, p.letra), 0) >= p.min) out.danio += p.n; break",
     "energiasDe(x, p.letra), 0) > p.min) out.danio += p.n; break"),
    (PAR, '«6 premios o menos» no cuenta el 6',
     "p.lista.includes(r.premios) : r.premios <= p.max) out.danio += p.n; break",
     "p.lista.includes(r.premios) : r.premios < p.max) out.danio += p.n; break"),
    (PAR, '«más premios que tu rival» al revés',
     "        case 'siMasPremios': if (s.premios.length > r.premios) out.danio += p.n; break",
     "        case 'siMasPremios': if (s.premios.length < r.premios) out.danio += p.n; break"),
    (PAR, 'el coste de retirada no multiplica',
     "out.danio -= p.n * (op && ra ? op.costeDeRetirada(ra) : 0); break",
     "out.danio -= p.n; break"),
    (PAR, '«sin contadores» siempre se cumple',
     "        case 'siPropioSinDanio': if (!slot.danio) out.danio += p.n; break",
     "        case 'siPropioSinDanio': out.danio += p.n; break"),
    (PAR, '«si no está Quemado, no hace nada» no mira',
     "        case 'nadaSiNoEstado': if (!ra?.estados?.includes(p.estado)) { out.nada = true; out.danio = 0 } break",
     "        case 'nadaSiNoEstado': break"),
    (PAR, '«Beldum y Metang» con uno basta',
     "    .every((n) => p.s.banca.some((x) => nombres(p.cartaDe(x)).includes(n)))",
     "    .some((n) => p.s.banca.some((x) => nombres(p.cartaDe(x)).includes(n)))"),
    (PAR, '«3 cartas o menos en tu baraja» no cuenta el 3',
     "        case 'siMazoMenos': if (s.mazo.length <= p.max) out.danio += p.n; break",
     "        case 'siMazoMenos': if (s.mazo.length < p.max) out.danio += p.n; break"),
    (PAR, 'si no llegan las 6 Planta, se descartan igual',
     "            if (vale.length < p.exacto) { out.descartadas = 0; break }\n",
     ""),
    (PAR, '«a cada uno de los Pokémon del rival» se queda en el activo',
     "          out.objetivos = [ra, ...r.banca].filter((d) => d && (!p.soloEx || d.ex))",
     "          out.objetivos = [ra].filter((d) => d && (!p.soloEx || d.ex))"),
    (PAR, '«a uno de los Pokémon ex en banca» deja elegir a cualquiera',
     "          const lista = (p.soloBanca ? r.banca : [ra, ...r.banca]).filter((d) => d && (!p.soloEx || d.ex))",
     "          const lista = (p.soloBanca ? r.banca : [ra, ...r.banca]).filter((d) => d)"),
    (PAR, '«a uno por cada energía» no multiplica',
     "const veces = p.porEnergia ? energiasDe(slot, p.letra) : p.porContadores",
     "const veces = p.porEnergia ? 1 : p.porContadores"),
    (PAR, '«al nuevo Pokémon Activo» no fija el daño',
     "        case 'fijarDanio': out.danio = p.n; break",
     "        case 'fijarDanio': break"),
    (PAR, '«si lo haces, te haces 50» no se hace',
     "            out.despues.push({ t: 'danioPropio', n: p.propio })\n",
     ""),
    (PAR, 'una moneda por energía es una moneda',
     "if (p.porEnergia) for (let i = energiasDe(slot, p.letra); i > 0; i--)",
     "if (p.porEnergia) for (let i = 1; i > 0; i--)"),

    # ── Lo de después (efectosPorTexto) ──
    (PAR, '«por cada cara, X» hace X todas las veces',
     "          for (let i = 0; i < caras; i++) for (const q of p.pasos) await hacer(q)",
     "          for (let i = 0; i < (p.n || 1); i++) for (const q of p.pasos) await hacer(q)"),
    (PAR, 'los contadores van también a los que no tenían',
     "case 'contadoresCadaDanado': for (const d of [ra, ...r.banca].filter((x) => x && x.danio > 0))",
     "case 'contadoresCadaDanado': for (const d of [ra, ...r.banca].filter((x) => x))"),
    (PAR, 'los contadores repartidos cuentan como puntos',
     "for (const d of objetivos) if (reparto?.[d.id]) this.danioAlRival(d, reparto[d.id] * 10, { contadores: true })",
     "for (const d of objetivos) if (reparto?.[d.id]) this.danioAlRival(d, reparto[d.id], { contadores: true })"),
    (PAR, 'lo que no dice «puedes» también se pregunta',
     "          if (p.opcional && !(await ui.confirmar({ titulo: ataque.name, texto: `¿Devuelves",
     "          if (!(await ui.confirmar({ titulo: ataque.name, texto: `¿Devuelves"),
    (PAR, '«no puede retirarse en tu próximo turno» caduca ya',
     "        case 'noRetiraSiguiente': slot.noRetirarHasta = s.turno + 1;",
     "        case 'noRetiraSiguiente': slot.noRetirarHasta = s.turno;"),
    (PAR, 'el daño hecho al activo no se apunta',
     "    } else {\n      s.flags.danioHecho = await this.danioDeAtaque(slot, danio, ui, calculo.mods)",
     "    } else {\n      await this.danioDeAtaque(slot, danio, ui, calculo.mods)"),
    (PAR, 'el bono de Puño Meteoro llega un turno tarde',
     "          slot.bonoAtaque = { turno: s.turno + 1, nombre: p.nombre, n: p.n, por }",
     "          slot.bonoAtaque = { turno: s.turno + 2, nombre: p.nombre, n: p.n, por }"),
    (PAR, '«cura a cada uno de tu banca» cura también al activo',
     "        case 'curarBanca': for (const d of s.banca) this.curar(d, p.n); break",
     "        case 'curarBanca': for (const d of this.enJuego) this.curar(d, p.n); break"),
    (PAR, '«también hace 40 a uno de TU banca» no lo hace',
     "en banca`, p.k)) this.ponerDanio(d, p.n, { motivo: ataque.name }); break",
     "en banca`, p.k)) void d; break"),
    (PAR, '«una carta que evolucione de este Pokémon» no se puede elegir',
     "elegibles: s.mazo.filter((u) => evolucionaDe(this.carta(u), c)), min: 0, max: 1, zona: 'mazo' })",
     "elegibles: [], min: 0, max: 1, zona: 'mazo' })"),
    (PAR, '«Pokémon de tu descarte» trae objetos',
     "          const DE_CLASE = { 'pokémon': esPokemon,",
     "          const DE_CLASE = { 'pokémon': esObjeto,"),
    (PAR, 'la energía buscada en el mazo no se une',
     "            this.unirEnergia(u, d, { desde: 'mazo' })\n",
     ""),
    (PAR, 'la energía del descarte no se une',
     "            this.unirEnergia(u, d, { desde: 'descarte' })\n",
     ""),
    (PAR, 'la energía de la mano no se une',
     "          this.unirEnergia(el[0], lista.find((x) => x.id === id), { desde: 'mano' })\n",
     ""),
    (PAR, 'la moneda del Ataque Arena caduca antes de su turno',
     "          ra.monedaAtaque = { turno: op.s.turno + 1, por }",
     "          ra.monedaAtaque = { turno: op.s.turno, por }"),
    (PAR, 'al atacar no se lanza la moneda del Ataque Arena',
     "    if (slot.monedaAtaque?.turno === s.turno && !this.moneda()) {",
     "    if (false) {"),
    (PAR, '«si vas primero, puedes usarlo» no levanta la regla',
     "    if (this.primerTurnoDelPrimero && !puedePrimero) return",
     "    if (this.primerTurnoDelPrimero) return"),

    # ── Habilidades ──
    (PAR, 'Robustez no aguanta',
     "      const aguante = cantidad >= ps && this.oponente.rasgosDe(objetivo, 'aguante')[0]",
     "      const aguante = false"),
    (PAR, 'Robustez aguanta aunque ya tenga daño',
     "    if (this.oponente && this.s.flags.enAtaque && !contadores && objetivo.danio === 0) {",
     "    if (this.oponente && this.s.flags.enAtaque && !contadores) {"),
    (PAR, 'Poltchageist recibe daño en la banca',
     "      const refugio = this.rasgosDe(slot, 'refugioEnBanca')[0]",
     "      const refugio = null"),
    (PAR, 'Yveltal no impide curarse',
     "    const cierra = slot === this.s.activo && this.oponente?.rasgosEnJuego('sinCurarRivalActivo')[0]",
     "    const cierra = null"),
    (PAR, 'Slowpoke se confunde',
     "      const inmune = op.rasgosDe(r, 'inmuneA').find((x) => !x.estado || x.estado === e)",
     "      const inmune = null"),
    (PAR, 'Kyurem solo mira el nombre inglés',
     "const conNombre = (u) => [op.carta(u)?.name, op.carta(u)?.name_es].some(",
     "const conNombre = (u) => [op.carta(u)?.name].some("),
    (EFE, 'Drilbur se lleva la Lucha a la mano',
     "{ titulo: 'Hasta 3 Energías Lucha básicas al descarte', filtro: basicaDe('F'), max: 3, destino: 'descarte' }",
     "{ titulo: 'Hasta 3 Energías Lucha básicas al descarte', filtro: basicaDe('F'), max: 3 }"),

    # ── Usar el ataque de otro ──
    (EFE, 'se elige el ataque y no se usa',
     "  if (o) await p.ejecutarAtaque(s, o.c, o.a, ui)\n",
     ""),
    (EFE, 'Slowking no usa el de un Pokémon sin regla',
     "        if (!esPokemon(c) || tieneRegla(c)) {",
     "        if (true) {"),

    # ── Leer y traducir ──
    (TXT, '«Put an Energy… into their hand» exige «you may»',
     "  [/^(you may )?put (an?|\\d+) energy attached to your opponent's active pokémon into their hand$/",
     "  [/^(you may )put (an?|\\d+) energy attached to your opponent's active pokémon into their hand$/"),
    (ES, '«Pon 1 Energía…» no se traduce',
     "[new RegExp(`^(puedes )?(?:pon|poner) ${N} energías? unidas?",
     "[new RegExp(`^(puedes )?poner? ${N} energías? unidas?"),
    (ES, '«por cada cara, X» no se traduce',
     "    const dentro = alIngles(m[1])\n    return dentro ? `for each heads, ${dentro}` : null",
     "    const dentro = null\n    return dentro ? `for each heads, ${dentro}` : null"),
    (ES, '«Cambia 1 de los Pokémon en Banca … por el Pokémon que esté en el Puesto Activo» no se traduce',
     "por (?:el pokémon que esté en el|su) puesto activo$/",
     "por su puesto activo$/"),
]

rigor_comun.correr(MUTACIONES, 'test-tanda-625.mjs')
